name: Build and Push Docker Image

on:
  push:
    branches: [citus]
  pull_request:
    branches: [citus]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/pgvector-citus

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.citus
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pgvector-citus:latest
            ghcr.io/${{ github.repository_owner }}/pgvector-citus:${{ github.sha }}
